"""Add sponsor_id to cart items

Revision ID: 49395ba717d4
Revises: 6d6d8d39e31f
Create Date: 2025-10-28 04:02:13.322717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49395ba717d4'
down_revision = '6d6d8d39e31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('NOTIFICATIONS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('NOTIFICATIONS_RECIPIENT_FK'))
        batch_op.create_foreign_key(None, 'USERS', ['RECIPIENT_CODE'], ['USER_CODE'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NOTIFICATIONS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('NOTIFICATIONS_RECIPIENT_FK'), ['RECIPIENT_CODE'], unique=False)

    with op.batch_alter_table('IMPERSONATION_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ACTION', mysql.VARCHAR(length=20), nullable=False, comment='start or stop'))
        batch_op.add_column(sa.Column('TARGET_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ACTOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('CREATED_AT', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('IMPERSONATION_TARGET_FK'), 'USERS', ['TARGET_ID'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('IMPERSONATION_ACTOR_FK'), 'USERS', ['ACTOR_ID'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('created_at')
        batch_op.drop_column('action')
        batch_op.drop_column('target_id')
        batch_op.drop_column('actor_id')

    with op.batch_alter_table('CART_ITEMS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sponsor_id')

    # ### end Alembic commands ###
