"""Add license number to driver application

Revision ID: 6d6d8d39e31f
Revises: 9cb1ca976b09
Create Date: 2025-10-27 22:38:00.357999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d6d8d39e31f'
down_revision = '9cb1ca976b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('SPONSORS', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('SPONSORS_USERS_FK'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'USERS', ['SPONSOR_ID'], ['USER_CODE'], ondelete='CASCADE')

    with op.batch_alter_table('WISHLIST_ITEMS', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('WISHLIST_ITEMS_USERS_FK'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'USERS', ['user_id'], ['USER_CODE'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WISHLIST_ITEMS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('WISHLIST_ITEMS_USERS_FK'), 'USERS', ['user_id'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('SPONSORS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('SPONSORS_USERS_FK'), 'USERS', ['SPONSOR_ID'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('NOTIFICATIONS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('NOTIFICATIONS_RECIPIENT_FK'), 'USERS', ['RECIPIENT_CODE'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('NOTIFICATIONS_SENDER_FK'), 'USERS', ['SENDER_CODE'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('IMPERSONATION_LOG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ACTOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ACTION', mysql.VARCHAR(length=20), nullable=False, comment='start or stop'))
        batch_op.add_column(sa.Column('TARGET_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('CREATED_AT', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('IMPERSONATION_ACTOR_FK'), 'USERS', ['ACTOR_ID'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('IMPERSONATION_TARGET_FK'), 'USERS', ['TARGET_ID'], ['USER_CODE'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('created_at')
        batch_op.drop_column('action')
        batch_op.drop_column('target_id')
        batch_op.drop_column('actor_id')

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.drop_column('LICENSE_NUMBER')

    # ### end Alembic commands ###
