"""Re-creating initial migration correctly

Revision ID: 9cb1ca976b09
Revises:
Create Date: 2025-10-27 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb1ca976b09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the only new table that is needed
   # op.create_table('DRIVER_SPONSOR_ASSOCIATION',
   # sa.Column('driver_id', sa.Integer(), nullable=False),
   # sa.Column('sponsor_id', sa.Integer(), nullable=False),
   # sa.Column('points', sa.Integer(), nullable=True),
   # sa.ForeignKeyConstraint(['driver_id'], ['DRIVERS.DRIVER_ID'], ),
   # sa.ForeignKeyConstraint(['sponsor_id'], ['SPONSORS.SPONSOR_ID'], ),
   # sa.PrimaryKeyConstraint('driver_id', 'sponsor_id')
    #)

    # Apply necessary changes to the USERS table
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('LOCKED_REASON',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('TOTP_SECRET',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=True)
        # Only try to drop the column if it exists
        try:
            batch_op.drop_column('POINTS')
        except Exception:
            # Ignore if the column is already gone
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('POINTS', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('TOTP_SECRET',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('LOCKED_REASON',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.drop_table('DRIVER_SPONSOR_ASSOCIATION')
    # ### end Alembic commands ###